version: '3.4'

services:
  redis:
    container_name: "redis_${NAME}"
    hostname: redis
    image: dimvic/redis:7-alpine-tls-acl
    volumes:
      - "./conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./conf/redis.acl:/usr/local/etc/redis/redis.acl"
      - "redis_data:/data"
    ports:
      - "6380:6379"
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    restart: always

volumes:
  redis_data:
